### ISSUE TITLE
[Request] Choose Custom Images

### ISSUE THREAD

**Issue by MiguelGuthridge** [rocksdanister/shadertoy-heartfelt#1]
I don't know enough HTML/JS to be able to add my own images manually. Maybe a JSON file where we can add the locations of images would be nice?

**Comment by rocksdanister** [comment]
With latest v2 update, You only need to copy the images to the folder and reopen the customise menu:
https://www.reddit.com/r/LivelyWallpaper/comments/fjc92g/cutomisable_rain_wallpaper_v2_wallpaper/

**Comment by MiguelGuthridge** [comment]
This means that Lively isn't shipping with V2 of this... I literally installed it a few hours ago.

**Comment by rocksdanister** [comment]
yes the included wallpaper is old, you will have to download v2.

The included wallpapers will change with lively v1.0 onwards (next update).
